# Generated by Django 5.1 on 2024-09-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.CharField(default='https://imgur.com/yaSgHpW', max_length=255),
        ),
    ]
