# Generated by Django 5.1 on 2024-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_link',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
